#!/usr/bin/env python
import sys
from dolphinido.console import (
	input,
    fingerprint, 
    radio, 
    recognize_file, 
    recognize_audio, 
    recognize_radio
)

input = input()
args = input.parse_args()

if not args:
	input.print_help()
	sys.exit(0)


if __name__ == '__main__':

	try:
		if args.fingerprint:
			fingerprint(args)
			
		elif args.radio:
			radio(args)
			
		elif args.recogfile:
			recognize_file(args)

		elif args.recogmic:
			recognize_audio(args)

		elif args.recogradio:
			recognize_radio(args)

	except KeyboardInterrupt:
		print("Process finished")
